create or replace TABLE CONFIG.SOURCE (
	SOURCEID VARCHAR(36) NOT NULL DEFAULT LOWER(UUID_STRING()),
	SOURCENAME VARCHAR(255) NOT NULL,
	SOURCEDESCRIPTION VARCHAR(16777216),
	SOURCETYPEID NUMBER(38,0) NOT NULL,
	FORMATTYPEID NUMBER(38,0) NOT NULL,
	SOURCEPATH VARCHAR(1000) NOT NULL,
	SECRETID VARCHAR(36),
	CONNECTIONID NUMBER(38,0),
	ACTIVE BOOLEAN NOT NULL,
	CREATEDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	MODIFIEDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ISDELETE BOOLEAN,
	constraint PK_SOURCE primary key (SOURCEID),
	constraint UQ_SOURCE_SOURCENAME unique (SOURCENAME)
);
